### ISSUE TITLE
No module named 'packaging' found

### ISSUE THREAD

**Issue by p-galligan** [barseghyanartur/django-nine#11]
We're using django-nine 0.2.6 as installed in a `requirements.txt` file via `django-elasticsearch-dsl-drf~=0.22` in a `requirements.in` file in a dockerized django application.

It appears the required packaging module isn't getting installed as necessary.

Here's a snippet of the docker-compose error message:

> File "/usr/local/lib/python3.10/site-packages/django_elasticsearch_dsl_drf/__init__.py", line 12, in <module>
>> from django_nine import versions
> File "/usr/local/lib/python3.10/site-packages/django_nine/versions.py", line 6, in <module>
>> from packaging.version import Version
> ModuleNotFoundError: No module named 'packaging'

We are running this in concert with django-elasticsearch-dsl-drf version 0.22.5. 

Current workaround is adding packaging directly to the `requirements.in` file, but that should not be necessary. `pip-compile` is not picking up the change from `distutil` to `packaging` when django-nine is installed as a requirement via another package.

**Comment by barseghyanartur** [comment]
Fixed in 0.2.7.
