### ISSUE TITLE
Rename installed package directory

### ISSUE THREAD

**Issue by jayvdb** [barseghyanartur/django-nine#2]
This installs into directory 'nine', which conflicts with the PyPI package 'nine'.

I've packaged this up as https://build.opensuse.org/package/show/home:jayvdb:django/python-django-nine

where I needed to note that it conflicts with the more commonly used python-nine package.

**Comment by barseghyanartur** [comment]
@jayvdb:

I think this package is currently used more than `nine`. I made my opinion on the number of downloads per day/week.

- https://pepy.tech/project/django-nine
- https://pepy.tech/project/nine

But I agree. I can rename the namespace from `nine` to `django_nine`.

**Comment by jayvdb** [comment]
I agree regarding the usefulness/used-ness, but I guess 'nine' has been around longer, and would have more users except that it was competing with `six` and the like.

Anyways convention is that package directories should be named close to the PyPI name where possible.  Principle of least surprise.  Django apps often dont prefix their directories with `django_` but they are rarely aiming at high degrees of compatibility - they expect to be installed into a python venv with only django and a few other apps.

This internal rename will need documentation, as callers will need to adjust their import to

```
try:
    import django_nine
except ImportError:
    import nine as django_nine
    # verify it is the correct one by referencing a name only present in django_nine
    django_nine.foo
```

**Comment by jayvdb** [comment]
Another approach is to also install a compatibility shim in `nine` , which transparently uses `django_nine`.  OS packagers could then drop that bit.  This would give the users a bit of time to adjust to the rename, and then the shim dropped at a later time.

**Comment by jayvdb** [comment]
btw https://github.com/spapas/django-package-compatibility-matrix is quite useful , and could be added to the readme here.

Im currently also looking at https://github.com/zapier/django-birdcage and https://github.com/arteria/django-compat to see if they hold anything useful.  Are you aware of any other similar packages?

**Comment by barseghyanartur** [comment]
@jayvdb:

A start has been made in [v0.2](https://github.com/barseghyanartur/django-nine/tree/v0.2) branch. I'll finish it soon.

**Comment by barseghyanartur** [comment]
@jayvdb:

Done in version 0.2. As of 0.2 `nine` is still present for backwards compatibility. The active namespace is changed from `nine` to `django_nine`. In version 0.3 `nine` will be removed.

**Comment by jayvdb** [comment]
Thanks.  https://build.opensuse.org/request/show/703710 submitted to upgrade openSUSE's version.

btw, https://github.com/pakal/django-compat-patcher is now updated to working with Django 2 - a very useful tool.

https://github.com/arteria/django-compat/issues/66 and https://github.com/django-xxx/django-six/issues/1 are still not ready for use.
